#!/usr/bin/env bash
# =============================================================================
# configure_permissions.sh
# ────────────────────────
# Checks and configures host system prerequisites for running the
# Firecracker MicroVM sandbox driver.
#
# What it does:
#   1. Checks /dev/kvm exists and is accessible by the current user.
#   2. Installs a passwordless sudoers rule for the specific `ip` commands
#      needed by TAPDeviceManager (ip tuntap, ip link, ip addr).
#   3. Verifies the Firecracker binary, kernel, and rootfs artifacts exist.
#   4. Runs a quick TAP sudo test to confirm the sudoers rule is active.
#
# Usage:
#   bash sandbox/configure_permissions.sh          # check + install
#   bash sandbox/configure_permissions.sh --check   # check only (no changes)
#
# Security:
#   The sudoers rule grants passwordless access ONLY to:
#     - /sbin/ip tuntap add *
#     - /sbin/ip link set *
#     - /sbin/ip link del *
#     - /sbin/ip addr add *
#   No other commands are allowed. The rule is installed in
#   /etc/sudoers.d/lifa-fuzz and validated with visudo before writing.
# =============================================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────

GREEN="\033[92m"; RED="\033[91m"; YELLOW="\033[93m"; CYAN="\033[96m"; BOLD="\033[1m"; RESET="\033[0m"

# ── Configuration ──────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHECK_ONLY=false
SUDOERS_FILE="/etc/sudoers.d/lifa-fuzz"
TMP_SUDOERS="/tmp/lifa-fuzz-sudoers.tmp"

if [[ "${1:-}" == "--check" ]]; then
    CHECK_ONLY=true
fi

# ── Resolve ip binary path ────────────────────────────────────────────────

IP_PATH="$(command -v ip 2>/dev/null || echo "/sbin/ip")"
CURRENT_USER="${SUDO_USER:-${USER}}"

# ── Tracking ──────────────────────────────────────────────────────────────

declare -a RESULTS=()

pass() { RESULTS+=("PASS:$1"); echo -e "  ${GREEN}✓ PASS${RESET}  $1"; }
fail() { RESULTS+=("FAIL:$1"); echo -e "  ${RED}✗ FAIL${RESET}  $1 ${RED}— $2${RESET}"; }
warn() { RESULTS+=("WARN:$1"); echo -e "  ${YELLOW}⚠ WARN${RESET}  $1 ${YELLOW}— $2${RESET}"; }

# ── Banner ────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}============================================================"
echo -e "  LIFA-Fuzz Firecracker — Permissions & Prerequisites"
echo -e "============================================================${RESET}"
echo ""
echo "  User:       ${CURRENT_USER}"
echo "  ip path:    ${IP_PATH}"
echo "  Check only: ${CHECK_ONLY}"
echo ""

# ══════════════════════════════════════════════════════════════════════════
# Phase 1: /dev/kvm
# ══════════════════════════════════════════════════════════════════════════

echo -e "${CYAN}${BOLD}Phase 1: /dev/kvm${RESET}"
echo ""

if [[ -c /dev/kvm ]]; then
    pass "/dev/kvm exists"

    if [[ -r /dev/kvm && -w /dev/kvm ]]; then
        pass "/dev/kvm is readable+writable by ${CURRENT_USER}"
    else
        KVM_GROUP="$(stat -c '%G' /dev/kvm 2>/dev/null || echo 'kvm')"
        fail "/dev/kvm is NOT accessible by ${CURRENT_USER}" \
            "Fix: sudo usermod -aG ${KVM_GROUP} ${CURRENT_USER} && newgrp ${KVM_GROUP}"
    fi
else
    fail "/dev/kvm does NOT exist" \
        "Fix: sudo modprobe kvm_intel  (or kvm_amd for AMD CPUs)"
fi

echo ""

# ══════════════════════════════════════════════════════════════════════════
# Phase 2: Sudoers rule for TAP commands
# ══════════════════════════════════════════════════════════════════════════

echo -e "${CYAN}${BOLD}Phase 2: Sudoers rule for TAP device management${RESET}"
echo ""

# Generate the sudoers content
SUDOERS_CONTENT="# LIFA-Fuzz: passwordless ip commands for TAP device management
# Auto-generated by sandbox/configure_permissions.sh
# Only the specific ip subcommands needed by TAPDeviceManager are allowed.
${CURRENT_USER} ALL=(root) NOPASSWD: ${IP_PATH} tuntap add *
${CURRENT_USER} ALL=(root) NOPASSWD: ${IP_PATH} link set *
${CURRENT_USER} ALL=(root) NOPASSWD: ${IP_PATH} link del *
${CURRENT_USER} ALL=(root) NOPASSWD: ${IP_PATH} addr add *"

# Check if already installed with identical content
if [[ -f "${SUDOERS_FILE}" ]]; then
    EXISTING="$(cat "${SUDOERS_FILE}" | grep -v '^#' | grep -v '^$')"
    NEW="$(echo "${SUDOERS_CONTENT}" | grep -v '^#' | grep -v '^$')"
    if [[ "${EXISTING}" == "${NEW}" ]]; then
        pass "Sudoers rule already installed (${SUDOERS_FILE})"
    else
        if [[ "${CHECK_ONLY}" == "true" ]]; then
            warn "Sudoers rule exists but differs" "Re-run without --check to update"
        else
            echo -e "  ${YELLOW}Sudoers rule exists but differs — updating...${RESET}"
        fi
    fi
fi

# Install or update
if [[ ! -f "${SUDOERS_FILE}" ]] || [[ "${CHECK_ONLY}" == "false" ]]; then
    if [[ "${CHECK_ONLY}" == "true" ]]; then
        if [[ ! -f "${SUDOERS_FILE}" ]]; then
            fail "Sudoers rule NOT installed" "Re-run without --check to install"
        fi
    else
        # Write to temp file
        echo "${SUDOERS_CONTENT}" > "${TMP_SUDOERS}"

        # Validate with visudo
        if command -v visudo &>/dev/null; then
            if visudo -c -f "${TMP_SUDOERS}" >/dev/null 2>&1; then
                pass "Sudoers file syntax is valid"

                # Install
                sudo cp "${TMP_SUDOERS}" "${SUDOERS_FILE}" 2>/dev/null
                sudo chmod 440 "${SUDOERS_FILE}" 2>/dev/null
                rm -f "${TMP_SUDOERS}"
                pass "Sudoers rule installed → ${SUDOERS_FILE}"
            else
                rm -f "${TMP_SUDOERS}"
                fail "Sudoers file FAILED validation" \
                    "This should not happen — check visudo -c -f ${TMP_SUDOERS}"
            fi
        else
            rm -f "${TMP_SUDOERS}"
            fail "visudo command not found" \
                "Install: sudo apt install sudo  (or equivalent)"
        fi
    fi
fi

echo ""

# ══════════════════════════════════════════════════════════════════════════
# Phase 3: Artifacts
# ══════════════════════════════════════════════════════════════════════════

echo -e "${CYAN}${BOLD}Phase 3: Build artifacts${RESET}"
echo ""

FC_ENV="${PROJECT_ROOT}/sandbox/firecracker_env"

# Firecracker binary
if [[ -x "${FC_ENV}/firecracker" ]]; then
    FC_VERSION="$("${FC_ENV}/firecracker" --version 2>&1 | head -1 || echo 'unknown')"
    pass "firecracker binary  (${FC_VERSION})"
else
    fail "firecracker binary  NOT found" \
        "Fix: bash sandbox/setup_firecracker.sh"
fi

# Kernel
if [[ -f "${FC_ENV}/vmlinux" ]]; then
    pass "vmlinux kernel       ($(du -h "${FC_ENV}/vmlinux" | cut -f1))"
else
    fail "vmlinux kernel       NOT found" \
        "Fix: bash sandbox/firecracker_env/build_kernel.sh"
fi

# RootFS
if [[ -f "${FC_ENV}/rootfs.ext4" ]]; then
    pass "rootfs.ext4 image    ($(du -h "${FC_ENV}/rootfs.ext4" | cut -f1))"
else
    fail "rootfs.ext4 image    NOT found" \
        "Fix: bash sandbox/firecracker_env/build_rootfs.sh"
fi

echo ""

# ══════════════════════════════════════════════════════════════════════════
# Phase 4: Quick TAP sudo test
# ══════════════════════════════════════════════════════════════════════════

echo -e "${CYAN}${BOLD}Phase 4: TAP sudo verification${RESET}"
echo ""

if sudo -n "${IP_PATH}" link show lo >/dev/null 2>&1; then
    pass "sudo -n ip link show lo  (passwordless sudo works)"
else
    fail "sudo -n ip link show lo  (passwordless sudo NOT working)" \
        "Check: ${SUDOERS_FILE} exists and contains correct user"
fi

echo ""

# ══════════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════════

TOTAL=${#RESULTS[@]}
PASSING=0; FAILING=0
for r in "${RESULTS[@]}"; do
    if [[ "$r" == PASS:* ]]; then ((PASSING++)); else ((FAILING++)); fi
done

echo -e "${BOLD}============================================================${RESET}"
if [[ ${FAILING} -eq 0 ]]; then
    echo -e "  ${GREEN}${BOLD}ALL ${TOTAL} CHECKS PASSED${RESET}  — ready for Firecracker smoke test"
    echo ""
    echo "  Next: python sandbox/smoke_test_firecracker.py"
else
    echo -e "  ${RED}${BOLD}${FAILING} CHECK(S) FAILED${RESET}  out of ${TOTAL} total"
    echo ""
    echo "  Fix the FAIL items above, then re-run this script."
fi
echo -e "${BOLD}============================================================${RESET}"
echo ""

exit $((FAILING))
